ghum_skeleton = [
    [
        "RIGHT_HIP",
        "LEFT_HIP"
    ],
    [
        "RIGHT_HIP",
        "RIGHT_KNEE"
    ],
    [
        "RIGHT_KNEE",
        "RIGHT_ANKLE"
    ],
    [
        "RIGHT_ANKLE",
        "RIGHT_FOOT_INDEX"
    ],
    [
        "RIGHT_ANKLE",
        "RIGHT_HEEL"
    ],
    [
        "RIGHT_HEEL",
        "RIGHT_FOOT_INDEX"
    ],
    [
        "LEFT_HIP",
        "LEFT_KNEE"
    ],
    [
        "LEFT_KNEE",
        "LEFT_ANKLE"
    ],
    [
        "LEFT_ANKLE",
        "LEFT_FOOT_INDEX"
    ],
    [
        "LEFT_ANKLE",
        "LEFT_HEEL"
    ],
    [
        "LEFT_HEEL",
        "LEFT_FOOT_INDEX"
    ],
    [
        "RIGHT_HIP",
        "RIGHT_SHOULDER"
    ],
    [
        "LEFT_HIP",
        "LEFT_SHOULDER"
    ],
    [
        "RIGHT_SHOULDER",
        "LEFT_SHOULDER"
    ],
    [
        "RIGHT_SHOULDER",
        "RIGHT_ELBOW"
    ],
    [
        "RIGHT_ELBOW",
        "RIGHT_WRIST"
    ],
    [
        "RIGHT_WRIST",
        "RIGHT_THUMB"
    ],
    [
        "RIGHT_WRIST",
        "RIGHT_PINKY"
    ],
    [
        "RIGHT_WRIST",
        "RIGHT_INDEX"
    ],
    [
        "RIGHT_PINKY",
        "RIGHT_INDEX"
    ],
    [
        "LEFT_SHOULDER",
        "LEFT_ELBOW"
    ],
    [
        "LEFT_ELBOW",
        "LEFT_WRIST"
    ],
    [
        "LEFT_WRIST",
        "LEFT_THUMB"
    ],
    [
        "LEFT_WRIST",
        "LEFT_PINKY"
    ],
    [
        "LEFT_WRIST",
        "LEFT_INDEX"
    ],
    [
        "LEFT_PINKY",
        "LEFT_INDEX"
    ],
    [
        "RIGHT_EAR",
        "RIGHT_EYE_OUTER"
    ],
    [
        "RIGHT_EYE_OUTER",
        "RIGHT_EYE"
    ],
    [
        "RIGHT_EYE",
        "RIGHT_EYE_INNER"
    ],
    [
        "RIGHT_EYE_INNER",
        "NOSE"
    ],
    [
        "LEFT_EAR",
        "LEFT_EYE_OUTER"
    ],
    [
        "LEFT_EYE_OUTER",
        "LEFT_EYE"
    ],
    [
        "LEFT_EYE",
        "LEFT_EYE_INNER"
    ],
    [
        "LEFT_EYE_INNER",
        "NOSE"
    ],
    [
        "MOUTH_LEFT",
        "MOUTH_RIGHT"
    ]
]
